### PR TITLE
Add NUM_THREADS configuration option

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

**Comment by KristofferC** [comment]
The name "REPL threads" sounds a bit odd to me. Why include REPL at all?

**Comment by ZacLN** [comment]
Because it's specific to the REPL (rather than the language server, test tasks, etc.). Happy to take other suggestions

**Comment by KristofferC** [comment]
I think the implementation should be such that it is equivalent to having the environment variable. Otherwise, how would you eg run the tests of a package threaded?

**Comment by davidanthoff** [comment]
I've assigned this to v0.13.0, ok? Lets get v0.12.0 out with the feature set we have first :)

**Comment by davidanthoff** [comment]
So maybe call it just `NumThreads`, and then use it for more processes, I.e. test runs, doc build etc? The latter don’t have to be part of this PR, of course.

**Pull request merged**
