### PR TITLE
Run more tests as part of our CI

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by davidanthoff** [comment]
I'm also just going to merge as this doesn't touch any production code, just our CI testing story.

**Comment by aviatesk** [comment]
Why do we need `testenvironments` folder ? I don't see the reason for the indirection.

**Comment by davidanthoff** [comment]
For the test of `DebugAdapter` we need to make sure they use the local package versions in the repo and not something that is downloaded from the repository, so we need a Manifest to specify that. For the other two I guess we could in theory activate the package itself, but doesn't that create a Manifest.toml?

**Comment by aviatesk** [comment]
```
pkg> activate VSCodeServer
pkg> test
```
will create Manifest.toml in the root of VSCodeServer, and it would work as in an usual package.

**Comment by davidanthoff** [comment]
Yeah, and I don't really like these `Manifest.toml` files in package folders, I'm always worried that they have some unintended side-effect later on. I think generally we should try hard to have our extension folder be as much read-only as possible (to fully get there we should at some point move the depot for the LS out of it as well).

**Pull request merged**
