### PR TITLE
improve cell delimiter regex

### LINKED ISSUE #1256: discussion: change cell delimiter regex ?
Currently julia vscode extension uses `^##` as a cell delimiter regex, while from v0.12.5 we had modified Juno's default delimiter so that it won't recognize YAS style section headers as cells, and we ended up with `^##(?!#)` by default.
(if interested, see https://github.com/JunoLab/atom-julia-client/pull/721 or https://discourse.julialang.org/t/ann-juno-0-12-5/39744/2?u=aviatesk).
Maybe we also want to use this here as well ?

### PR DESCRIPTION
**Pull request by aviatesk**
- closes #1256

### CODE REVIEW

**Comment by pfitzseb** [comment]
Should we mention this somewhere (e.g. CHANGELOG.md) since it's techincally breaking?

**Comment by aviatesk** [comment]
ah, yes, I just remember we discussed that yesterday. Will do.

**Comment by davidanthoff** [comment]
I wonder, though, whether we should just merge this now and ship with the next patch release? We can still mention it when we make a big announcement for 0.16, but this seems small and harmless enough that we can just slip it in?

**Comment by aviatesk** [comment]
yeah, let's ship this in patch release.

**Pull request merged**
