### PR TITLE
fix ws for zero-dim arrays

### PR DESCRIPTION
**Pull request by pfitzseb**
Alternative to https://github.com/julia-vscode/julia-vscode/pull/1351.

This both fixes the error with slightly better printing and makes sure the error isn't fatal.

### CODE REVIEW

**Comment by davidanthoff** [comment]
I'll merge as soon as we have shipped v0.16.

**Comment by davidanthoff** [comment]
@pfitzseb can you resolve the merge conflicts?

**Comment by pfitzseb** [comment]
Done.

**Comment by aviatesk** [comment]
More resolved.

**Pull request merged**
