### PR TITLE
Add envs for julia v1.9

### PR DESCRIPTION
**Pull request by IanButterworth**
The extension doesn't work on julia master because of some stdlib changes. Even though v1.9 isn't released, it would be helpful to have this working

I just copied the v1.8 envs and ran `Pkg.resolve` 

```
(v1.9) pkg> resolve
  No Changes to `~/Documents/GitHub/julia-vscode/scripts/environments/languageserver/v1.9/Project.toml`
    Updating `~/Documents/GitHub/julia-vscode/scripts/environments/languageserver/v1.9/Manifest.toml`
  [8bb1440f] + DelimitedFiles v1.9.0
  [10745b16] ~ Statistics ⇒ v1.9.0
  [fa267f1f] ↑ TOML v1.0.0 ⇒ v1.0.3
  [e66e0078] ↑ CompilerSupportLibraries_jll v0.5.2+0 ⇒ v1.0.1+0
  [14a3606d] ↑ MozillaCACerts_jll v2022.2.1 ⇒ v2022.10.11
  [4536629a] ↑ OpenBLAS_jll v0.3.20+0 ⇒ v0.3.21+0
  [bea87d4a] + SuiteSparse_jll v5.10.1+0
  [83775a58] ↑ Zlib_jll v1.2.12+3 ⇒ v1.2.13+0
  [8e850b90] ↑ libblastrampoline_jll v5.1.1+0 ⇒ v5.2.0+0

(v1.9) pkg> activate  /Users/ian/Documents/GitHub/julia-vscode/scripts/environments/pkgdev/v1.9
  Activating project at `~/Documents/GitHub/julia-vscode/scripts/environments/pkgdev/v1.9`

(v1.9) pkg> resolve
   Installed Tokenize ──────── v0.5.24
   Installed PkgDev ────────── v1.7.2
   Installed RegistryTools ─── v1.8.1
   Installed FilePathsBase ─── v0.9.19
   Installed Mustache ──────── v1.0.14
   Installed MbedTLS ───────── v1.1.5
   Installed PkgButlerEngine ─ v1.11.1
   Installed JuliaFormatter ── v1.0.9
   Installed Compat ────────── v4.2.0
   Installed DocumentFormat ── v4.0.3
   Installed CSTParser ─────── v3.3.6
  No Changes to `~/Documents/GitHub/julia-vscode/scripts/environments/pkgdev/v1.9/Project.toml`
    Updating `~/Documents/GitHub/julia-vscode/scripts/environments/pkgdev/v1.9/Manifest.toml`
  [fa267f1f] ↑ TOML v1.0.0 ⇒ v1.0.3
  [e66e0078] ↑ CompilerSupportLibraries_jll v0.5.2+0 ⇒ v1.0.1+0
  [14a3606d] ↑ MozillaCACerts_jll v2022.2.1 ⇒ v2022.10.11
  [4536629a] ↑ OpenBLAS_jll v0.3.20+0 ⇒ v0.3.21+0
  [83775a58] ↑ Zlib_jll v1.2.12+3 ⇒ v1.2.13+0
  [8e850b90] ↑ libblastrampoline_jll v5.1.1+0 ⇒ v5.2.0+0

(v1.9) pkg> activate /Users/ian/Documents/GitHub/julia-vscode/scripts/environments/sysimagecompile/v1.9
  Activating project at `~/Documents/GitHub/julia-vscode/scripts/environments/sysimagecompile/v1.9`

(v1.9) pkg> resolve
  No Changes to `~/Documents/GitHub/julia-vscode/scripts/environments/sysimagecompile/v1.9/Project.toml`
    Updating `~/Documents/GitHub/julia-vscode/scripts/environments/sysimagecompile/v1.9/Manifest.toml`
  [fa267f1f] ↑ TOML v1.0.0 ⇒ v1.0.3
  [14a3606d] ↑ MozillaCACerts_jll v2022.2.1 ⇒ v2022.10.11
  [83775a58] ↑ Zlib_jll v1.2.12+3 ⇒ v1.2.13+0
```

### CODE REVIEW

**Comment by IanButterworth** [comment]
This doesn't seem to be enough
```
[ Info: Starting the Julia Language Server
ERROR: LoadError: ArgumentError: Package DelimitedFiles [8bb1440f-4735-579b-a4ab-409b98df4dab] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

Stacktrace:
  [1] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1400
  [2] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1295
  [3] macro expansion
    @ ./loading.jl:1275 [inlined]
  [4] macro expansion
    @ ./lock.jl:267 [inlined]
  [5] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1238
  [6] top-level scope
    @ ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/Compat/src/deprecated.jl:23
```

**Comment by IanButterworth** [comment]
I guess DelimitedFiles needs to be added as a submodule to the package source cache too.

However, after manually copying it in to try it out I got this
```
[ Info: Starting the Julia Language Server
ERROR: LoadError: ArgumentError: Package LanguageServer does not have TestItemDetection in its dependencies:
```

**Comment by IanButterworth** [comment]
Another way around the DelimitedFiles issue is upgrading Compat to v4 after it was dropped in https://github.com/JuliaLang/Compat.jl/pull/767/files#diff-72ed386c2a0cd1d23c0968297e70023ed98c22490d146dd89fc91f48369bad4d

**Comment by davidanthoff** [comment]
These files are all auto-generated. To add a new Julia version it should be added to https://github.com/julia-vscode/julia-vscode/blob/69874c3e78c210f18a371a88059e2d65a5371293/src/scripts/updateDeps.ts#L93, but that will only work once there is a Juliaup version that has support for 1.9, which we don't have yet. Normally I start to add new minor Julia versions once a beta version is out, which I think is not the case for 1.9 yet, right?

**Comment by IanButterworth** [comment]
True. The issue I guess is that the fallback env is not compatible with 1.9/1.10. Perhaps the fallback shouldn't have a manifest? Would that be possible?

**Comment by davidanthoff** [comment]
I don’t think that would work because the manifest is actually the place where we store the relative paths to the packages that we ship with the extension.

Here is an idea: you could probably add a linked channel named 1.9 to Juliaup, and then the script here should work for 1.9 as well.

**Comment by pepijndevos** [comment]
How would I actually do this? I have master linked, and am now trying to install the extension from source. I'm basically doing this https://github.com/julia-vscode/julia-vscode/wiki/Updating-to-the-latest-version but that doesn't update the environments. and I found there is a `npm run updatedeps` command but it crashes in a myriad of ways depending on what I do, which I'm sure is just because I'm running it wrong or need to run something else first or whatever.

**Comment by davidanthoff** [comment]
I'm updating the update script right now, i.e. I'll handle this problem. I have one more question on this over at https://github.com/julia-vscode/julia-vscode/issues/3160.

**Pull request closed without merging**
