### PR TITLE
add cmd copy howto type

### PR DESCRIPTION
**Pull request by xgdgsc**
Add the command to copy how to type selected latex/emoji char to clipboard.

Fixes https://github.com/julia-vscode/julia-vscode/issues/3153

### CODE REVIEW

**Comment by davidanthoff** [comment]
Seems to me this should be implemented in the language server, there is no good reason why this should only work with a running REPL, right?

**Comment by xgdgsc** [comment]
I don' t know the statistics of how many people would run without REPL. If it' s in Language Server it would be better. I don' t know the performance impact if every hover tries to find this info versus on demand finding.

**Comment by pfitzseb** [comment]
Agreed, this should happen in the LS. We can create a lookup table for this, much like the REPL code does: https://github.com/JuliaLang/julia/blob/88230581592d5a80c636c6a3ad592076cd25e0e2/stdlib/REPL/src/docview.jl#L391-L410

**Comment by davidanthoff** [comment]
The main question is probably whether this info can just be added to the hover that is already returned? That seems the easiest and best solution?

**Comment by pfitzseb** [comment]
It can, and yes, agreed :)

**Comment by davidanthoff** [comment]
Ok, great, that should also actually make the implementation _much_ easier. @xgdgsc I think essentially you just need to make some changes to https://github.com/julia-vscode/LanguageServer.jl/blob/master/src/requests/hover.jl to get this working, without the need to define new messages, or make any other changes in the client itself.

**Pull request closed without merging**
