### PR TITLE
Simplify executable path lookup

### PR DESCRIPTION
**Pull request by pfitzseb**
Fixes https://github.com/julia-vscode/julia-vscode/issues/2294.

### CODE REVIEW

**Comment by davidanthoff** [comment]
This doesn't work with juliaup, `which` won't find the necessary binary. I had spent a fair bit of time trying to get things to work properly with `which` at some point on Windows, but that never really worked reliably... I think we should just try to get the entire extension to work with a command line string rather than requiring an absolute path to the Julia executable.

**Comment by davidanthoff** [comment]
I'll take a crack at getting this to work with just command line stuff.

**Comment by pfitzseb** [comment]
But why would juliaup run into this at all? Is it the `julia.exe` case? If so, we could just completely get rid of any path resolution here, no?

**Comment by davidanthoff** [comment]
Yes, that is what I'm trying to do right now on my machine: just don't try to resolve any paths at all. I'm about halfway through, I'd say :)

**Comment by pfitzseb** [comment]
One consideration is that the terminal link resolver uses the result of this function to find files with relative paths (e.g. from stacktraces). Shouldn't hold up any of this though; we can find other solutions for that.

**Comment by pfitzseb** [comment]
Closing in favor of #2341.

**Pull request closed without merging**
