### PR TITLE
#1659 multiprocessing fix

### PR DESCRIPTION
**Pull request by k4rt33k**
Address the issue reported in https://github.com/julia-vscode/julia-vscode/issues/1659

### CODE REVIEW

**Comment by rustyconover** [comment]
Lets try this instead:

```julia
@everywhere Base.push!(LOAD_PATH, joinpath(@__DIR__, "..", "packages"))
@everywhere if myid() == 1 using VSCodeServer end
@everywhere pop!(LOAD_PATH)
```

This assumes the master process has an id of 1.

**Comment by k4rt33k** [comment]
@rustyconover Works for me. 
@davidanthoff Does this solution seem reasonable to you?

**Comment by davidanthoff** [comment]
Wouldn't this still load `VSCodeServer` on all machines? I thought the problem is that if one runs `using VSCodeServer` on worker 1, then it always tries to load it on all other workers as well?

**Comment by pfitzseb** [comment]
No, `using` should be process-local, afaiu. Which is exactly what we want, so I'm not sure why #1659 happens (some other code might try to load it or something, I guess?).

**Comment by davidanthoff** [comment]
I think this was recently fixed with a different PR from @pfitzseb .

**Pull request closed without merging**
