### PR TITLE
Fix image-like size to always fit pane

### LINKED ISSUE #2288: Plot scaling regression
If I'm not remembering it wrong, in this PR https://github.com/julia-vscode/julia-vscode/pull/1882 I changed the scaling of plots in the plot pane, so that they always fit into the available space, either vertically or horizontally. I don't know when this changed, but it appears that in the current version, the vertical scaling is broken, so that an image that is too high is clipped at the bottom, instead of scaled down.

grafik

### PR DESCRIPTION
**Pull request by jkrumbiegel**
Fixes #2288.

For every PR, please check the following:
- [ ] End-user documentation check. If this PR requires end-user documentation, please add that at https://github.com/julia-vscode/docs.
- [ ] Changelog mention. If this PR should be mentioned in the CHANGELOG, please edit the CHANGELOG.md file in this PR.

### CODE REVIEW

**Comment by TonyLianLong** [comment]
Thanks for your contribution! It seems that only the code for plotting raw images are changed. Do you have any plans to change the code for other plotting libraries, too? I have personally tested this on my Mac and it works, and I believe it could be merged if there are no other things to modify at the same time for other types of images.

image
image

**Comment by jkrumbiegel** [comment]
What do you mean with other plotting packages? This will work for any png, svg, jpg. For something like Vega plots, I don't think it's good to scale them as they are interactive documents

**Comment by TonyLianLong** [comment]
> What do you mean with other plotting packages? This will work for any png, svg, jpg. For something like Vega plots, I don't think it's good to scale them as they are interactive documents

Sure. Makes sense.

**Review by TonyLianLong — APPROVED** [review]

**Comment by davidanthoff** [comment]
Yeah, that sounds reasonable: vega-lite and vega plots normally have a fixed size and we should not scale them, presumably. Beyond that, I'll let @pfitzseb decide :)

**Comment by jkrumbiegel** [comment]
@pfitzseb friendly bump :)

**Review by pfitzseb — APPROVED** [review]

**Pull request merged**
