### PR TITLE
unique pipe names

### PR DESCRIPTION
**Pull request by pfitzseb**
Might fix https://github.com/julia-vscode/julia-vscode/issues/1978. I don't think this will break anything, so might make sense to get in regardless.

For every PR, please check the following:
- [x] End-user documentation check. If this PR requires end-user documentation, please add that at https://github.com/julia-vscode/docs.
- [x] Changelog mention. If this PR should be mentioned in the CHANGELOG, please edit the CHANGELOG.md file in this PR.

### CODE REVIEW

**Comment by davidanthoff** [comment]
We had some problems at some point with pipe names that were too long, I think that was on Mac. I'm not sure, but we might just be at he limit with the old names? I'm wondering whether we should just take out the `pid`, and just go with name and random id?

**Comment by pfitzseb** [comment]
Hm, I kinda like the disambiguation by PID for debugging, but it's probably pretty unlikely to be necessary for multiple sessions.

Also, afaik Windows has the lowest maximum path length at 256 (although longer paths are possible nowadays).

**Comment by davidanthoff** [comment]
I'm pretty positive the problem was on MacOS. I guess one way we could try this is to make sure to have things in a crash reporting block where this is used, so that we at least would be informed if this is a problem on some user systems?

**Comment by pfitzseb** [comment]
Just pushed a commit that consistently uses `uuid()` instead of the PID everywhere (we were already doing that for the debugger, which seems to have worked just fine).

**Review by davidanthoff — APPROVED** [review]

**Pull request merged**
