### PR TITLE
configurable cell separator

### PR DESCRIPTION
**Pull request by aviatesk**

### CODE REVIEW

**Comment by pfitzseb** [comment]
See https://github.com/julia-vscode/julia-vscode/pull/777 for previous discussion on whether this should be configurable.

**Comment by aviatesk** [comment]
agh, thanks for the pointer, I think I have to make a habit of searching "previous" things seriously...

**Comment by pfitzseb** [comment]
FWIW, I would kinda like the default regex to change to `^##(?!#)`.

**Comment by aviatesk** [comment]
yeah, I prefer that. Maybe post as an issue separate from #1222 ? We already have many things to be discussed or reviewed in that PR.

**Pull request closed without merging**
