### PR TITLE
Only send supported scheme project files to LS

### LINKED ISSUE #3694: Extension crashes when starting tests
I'm using Julia 1.10.5 with VSCode extension v1.120.2.  I have used the test functionality in the past, but I intermittently see this problem after I press the "Run Tests" button in the extension.  The tests don't run and the extension crashes.  I am able to run the tests fine outside of the extension with `] test`.

```
 Error: Some Julia code in the VS Code extension crashed
└ @ Main ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/error_handler.jl:15
ERROR: SalsaWrappedException: Error encountered while executing Salsa derived function:
MethodError: no method matching lowercase(::Nothing)

Closest candidates are:
  lowercase(!Matched::AbstractString)
   @ Base strings/unicode.jl:623
  lowercase(!Matched::T) where T<:AbstractChar
   @ Base strings/unicode.jl:290


------ Salsa Trace -----------------
[1] @derived derived_testenv(::Runtime, JuliaWorkspaces.URIs2.URI("file", "", "/Users/ifiske/optos/OptosUtils.jl/test/kpi_tests.jl", nothing, nothing)::JuliaWorkspaces.URIs2.URI)
[2] @derived derived_project_folders(::Runtime)
[3] @derived derived_potential_project_folders(::Runtime)
[4] @derived derived_project_files(::Runtime)
------------------------------------

Stacktrace:
  [1] is_path_project_file(path::Nothing)
    @ JuliaWorkspaces ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/JuliaWorkspaces/src/fileio.jl:6
  [2] (::JuliaWorkspaces.var"#5#6")(file::JuliaWorkspaces.URIs2.URI)
    @ JuliaWorkspaces ./strings/string.jl:0
  [3] iterate(f::Base.Iterators.Filter{JuliaWorkspaces.var"#5#6", Set{JuliaWorkspaces.URIs2.URI}}, state::Int64)
    @ Base.Iterators ./iterators.jl:518
  [4] iterate
    @ ./generator.jl:44 [inlined]
  [5] grow_to!(dest::Vector{JuliaWorkspaces.URIs2.URI}, itr::Base.Generator{Base.Iterators.Filter{JuliaWorkspaces.var"#5#6", Set{JuliaWorkspaces.URIs2.URI}}, typeof(identity)}, st::Int64)
    @ Base ./array.jl:938
  [6] grow_to!
    @ ./array.jl:911 [inlined]
  [7] collect(itr::Base.Generator{Base.Iterators.Filter{JuliaWorkspaces.var"#5#6", Set{JuliaWorkspaces.URIs2.URI}}, typeof(identity)})
    @ Base ./array.jl:831
  [8] %%__user_derived_project_files
    @ ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/JuliaWorkspaces/src/layer_projects.jl:4 [inlined]
  [9] _memoized_lookup_internal(runtime::Salsa._TracingRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, key::Salsa.DerivedKey{typeof(JuliaWorkspaces.derived_project_files), Tuple{}})
    @ Salsa._DefaultSalsaStorage ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/default_storage.jl:257
 [10] memoized_lookup(rt::Salsa._TracingRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, dependency_key::Salsa.DerivedKey{typeof(JuliaWorkspaces.derived_project_files), Tuple{}})
    @ Salsa ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/Salsa.jl:694
 [11] memoized_lookup_unwrapped
    @ ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/Salsa.jl:721 [inlined]
 [12] derived_project_files
    @ ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/Salsa.jl:641 [inlined]
 [13] var"%%__user_derived_potential_project_folders"(rt::Salsa._TracingRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage})
    @ JuliaWorkspaces ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/JuliaWorkspaces/src/layer_projects.jl:8
 [14] _memoized_lookup_internal(runtime::Salsa._TracingRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, key::Salsa.DerivedKey{typeof(JuliaWorkspaces.derived_potential_project_folders), Tuple{}})
    @ Salsa._DefaultSalsaStorage ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/default_storage.jl:257
 [15] memoized_lookup(rt::Salsa._TracingRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, dependency_key::Salsa.DerivedKey{typeof(JuliaWorkspaces.derived_potential_project_folders), Tuple{}})
    @ Salsa ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/Salsa.jl:694
 [16] memoized_lookup_unwrapped
    @ ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/Salsa.jl:721 [inlined]
 [17] derived_potential_project_folders
    @ ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/Salsa.jl:641 [inlined]
 [18] var"%%__user_derived_project_folders"(rt::Salsa._TracingRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage})
    @ JuliaWorkspaces ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/JuliaWorkspaces/src/layer_projects.jl:113
 [19] _memoized_lookup_internal(runtime::Salsa._TracingRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, key::Salsa.DerivedKey{typeof(JuliaWorkspaces.derived_project_folders), Tuple{}})
    @ Salsa._DefaultSalsaStorage ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/default_storage.jl:257
 [20] memoized_lookup(rt::Salsa._TracingRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, dependency_key::Salsa.DerivedKey{typeof(JuliaWorkspaces.derived_project_folders), Tuple{}})
    @ Salsa ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/Salsa.jl:694
 [21] memoized_lookup_unwrapped
    @ ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/Salsa.jl:721 [inlined]
 [22] derived_project_folders
    @ ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/Salsa.jl:641 [inlined]
 [23] var"%%__user_derived_testenv"(rt::Salsa._TracingRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, uri::JuliaWorkspaces.URIs2.URI)
    @ JuliaWorkspaces ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/JuliaWorkspaces/src/layer_testitems.jl:106
 [24] _memoized_lookup_internal(runtime::Salsa._TracingRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, key::Salsa.DerivedKey{typeof(JuliaWorkspaces.derived_testenv), Tuple{JuliaWorkspaces.URIs2.URI}})
    @ Salsa._DefaultSalsaStorage ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/default_storage.jl:257
 [25] memoized_lookup(rt::Salsa._TopLevelRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, dependency_key::Salsa.DerivedKey{typeof(JuliaWorkspaces.derived_testenv), Tuple{JuliaWorkspaces.URIs2.URI}})
    @ Salsa ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/Salsa.jl:694
 [26] memoized_lookup_unwrapped
    @ ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/Salsa.jl:721 [inlined]
 [27] derived_testenv(rt::Salsa._TopLevelRuntime{Salsa.EmptyContext, Salsa._DefaultSalsaStorage.DefaultStorage}, uri::JuliaWorkspaces.URIs2.URI)
    @ JuliaWorkspaces ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/Salsa/src/Salsa.jl:641
 [28] get_test_env(jw::JuliaWorkspaces.JuliaWorkspace, uri::JuliaWorkspaces.URIs2.URI)
    @ JuliaWorkspaces ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/JuliaWorkspaces/src/public.jl:153
 [29] julia_get_test_env_request(params::LanguageServer.GetTestEnvRequestParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
    @ LanguageServer ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/LanguageServer/src/requests/testing.jl:2
 [30] (::LanguageServer.var"#108#109"{typeof(LanguageServer.julia_get_test_env_request), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::LanguageServer.GetTestEnvRequestParams)
    @ LanguageServer ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/LanguageServer/src/languageserverinstance.jl:307
 [31] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
    @ JSONRPC ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/JSONRPC/src/typed.jl:67
 [32] run(server::LanguageServerInstance; timings::Vector{Any})
    @ LanguageServer ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/LanguageServer/src/languageserverinstance.jl:444
 [33] run(server::LanguageServerInstance)
    @ LanguageServer ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/packages/LanguageServer/src/languageserverinstance.jl:317
 [34] top-level scope
    @ ~/.vscode/extensions/julialang.language-julia-1.120.2/scripts/languageserver/main.jl:189
 [35] include(mod::Module, _path::String)
    @ Base ./Base.jl:495
 [36] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:318
 [37] _start()
    @ Base ./client.jl:552
[Info  - 9:33:48 AM] Connection to server got closed. Server will restart.
true
[Error - 9:33:48 AM] Server process exited with code 1.
[ Info: Starting LS with Julia 1.10.5
```

`is_path_project_file(path::Nothing)` suggests that there is some `path` set to `nothing`, but I have no idea what path that would be.

### PR DESCRIPTION
**Pull request by davidanthoff**
Fixes #3694, alternative to https://github.com/julia-vscode/LanguageServer.jl/pull/1322.

@ianfiske, I think this fix here tackles the root cause of the bug you reported. Could you try whether this one here also fixes the problem for you? Thanks!

### CODE REVIEW

**Comment by ianfiske** [comment]
Thanks @davidanthoff !  Is there a quick way for me to test the branch?  I've tried some things but extension development is new to me and no luck so far.

**Comment by ianfiske** [comment]
Looks like you merged it so I can just wait until it's released and then easily test.

**Comment by davidanthoff** [comment]
Yep, new insider build should be out very soon: https://github.com/julia-vscode/julia-vscode/actions/runs/10947186158

**Comment by ianfiske** [comment]
Your fix worked.  Thank you!

**Pull request merged**
