### PR TITLE
use repl ast transforms on 1.5 and up

### LINKED ISSUE #1958: ast_transforms
The REPL in julia-vscode appears to not run `Base.active_repl_backend.ast_transforms` functions at the right time, kind of understandable since it's only available in 1.5+.

```
julia> show_ast(ex) = (@show ex.args[2].args[1:3]; ex)
show_ast (generic function with 1 method)

julia> pushfirst!(Base.active_repl_backend.ast_transforms, show_ast)
3-element Vector{Any}:
 show_ast (generic function with 1 method)
 revise_first (generic function with 1 method)
 softscope (generic function with 1 method)

julia> 1 + 2
(ex.args[2]).args[1:3] = Any[VSCodeServer.evalrepl, :Main, "1 + 2"]
3
```

From the above you can see that the functions in `ast_transforms` are getting passed the expression from https://github.com/julia-vscode/julia-vscode/blob/e96e9425dd8e9d120177d5e8635b5048c0d48b9b/scripts/packages/VSCodeServer/src/repl.jl#L72-L74 rather than the actual expression `:(1 + 2)`.

If it's feasible to fix this, and someone can point me in the general direction where things would need changing I'm happy to take a look at fixing this myself.

### PR DESCRIPTION
**Pull request by pfitzseb**
Fixes #1958.

For every PR, please check the following:
- [x] End-user documentation check. If this PR requires end-user documentation, please add that at https://github.com/julia-vscode/docs.
- [x] Changelog mention. If this PR should be mentioned in the CHANGELOG, please edit the CHANGELOG.md file in this PR.

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
Thanks, appears to solve it on my end.

**Review by davidanthoff — APPROVED** [review]

**Comment by pfitzseb** [comment]
Just gotta hope that people don't try to `push!` their own transforms and expect them to work properly :)

**Comment by MichaelHatherly** [comment]
Yeah, I'm `pushfirst!`ing mine to not a problem, and Revise also does that. It's unfortunate that there isn't some form of priority for the transforms to alleviate that issue.

**Comment by pfitzseb** [comment]
Same as the display system, actually (cf https://github.com/JuliaLang/julia/pull/30922).

**Pull request merged**
