### PR TITLE
feat: explicitly start current Julia version in debug mode

### PR DESCRIPTION
**Pull request by pfitzseb**

### CODE REVIEW

**Comment by davidanthoff** [comment]
Hm, do we really want this? Not clear to me what (good) scenario this would enable :)

**Comment by pfitzseb** [comment]
The scenario where I can develop the extension for 1.11 with juliaup. I thought about just making it a dev mode toggle though, which is probably better :shrug: Not entirely sure *how* to query whether the extension is being debugged though.

**Comment by davidanthoff** [comment]
Ha, well, that does seem important, didn't think of that ;) But yes, I think we should handle that via some non-user facing option. We could just add an env var to the launch config, but there is probably a better way to detect debug mode...

**Comment by pfitzseb** [comment]
We're using `process.env.DEBUG_MODE` elsewhere, so I'll push a PR with that instead.

**Review by davidanthoff — APPROVED** [review]

**Pull request merged**
